name: Release JAR

on:
  workflow_dispatch:

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn clean package -DskipTests
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target/*.jar