name: Release JAR

on:
  workflow_dispatch:

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Package
        run: mvn clean package -DskipTests
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar